config/routes.rb
KalendarniPlan::Application.routes.draw do

  root :to => 'plan#index'
      match 'createuser'=> 'plan#createuser',:via => [:post]
      match 'createsession'=> 'plan#createsession',:via => [:post]
      match 'createtitle'=> 'plan#createtitle',:via => [:post]

  match 'cabinet' => 'plan#cabinet'
  match 'view' => 'plan#kp_view'
  match 'print'=> 'plan#kp_print'
    
  match 'title'=> 'plan#kp_titl'
    match 'save_title'=> 'plan#save_title'

  match 'lib'=> 'plan#kp_lit'
    match 'save_lib'=> 'plan#save_lib'

  match 'body'=> 'plan#kp_body'
  

  #get "plan/whoareyou"
  
end

app/controllers/plan_controller.rb
#encoding: utf-8

class PlanController < ApplicationController
  def index
    if signed_in?
      redirect_to cabinet_path
    else
    @user=User.new
    end
  end
          
          def createuser  #создание пользователя
            @user = User.new(params[:user])
            if @user.save
              redirect_to cabinet_path
            else
              render 'index'
            end

          end
            
          def createsession #создание сессии при входе пользователя
            user = User.authenticate(params[:session][:nik], params[:session][:pas])
            if user.nil?
              flash.now[:error] = "Invalid email/password combination."
              render 'new'
            else
              sign_in user
              redirect_to cabinet_path
            end
          end

          def create?(model)
            model.save
          end
    
  def cabinet
    @user=User.find(current_user.id)
    @cabinet_plans=@user.kplans.all
  end

  def kp_titl
    id=params[:id]
    user=current_user.id
    if id.nil?
      id=plan_new(user)
    else
      id=plan_copy(id, user)
    end
    @ktitle=Ktitl.find_by_kplan_id(id)
  end

      def plan_copy(plan_id, user_id)
        plan=Kplan.new(user_id:user_id, predmet_comissia:User.find(user_id).predmet_comissia)
        plan.save
        new_id=plan.id
        title=Ktitl.find_by_kplan_id(plan_id).dup
        title.kplan_id=new_id
        title.save
        lib=Klit.find_by_kplan_id(plan_id).dup
        lib.kplan_id=new_id
        lib.save
        body=Kbody.where("kplan_id=?", plan_id)
        body.each do |page|
          newpage=page.dup
          newpage.kplan_id=new_id
          newpage.save
        end
        new_id
      end

      def plan_new(user_id)
        plan=Kplan.new(user_id:user_id, predmet_comissia:User.find(user_id).predmet_comissia)
        plan.save
        new_id=plan.id
        title=Ktitl.new(kplan_id:new_id)
        title.save
        lib=Klit.new(kplan_id:new_id)
        lib.save
        body=Kbody.new(kplan_id:new_id)
        body.save
        new_id
       end

      def save_title
        plan_title=Ktitl.find_by_kplan_id(params[:ktitle][:kplan_id])
        if plan_title.nil?
          plan_title=Ktitl.new(kplan_id:params[:ktitle][:kplan_id])
        end
        plan_title.pregmet=params[:ktitle][:pregmet]
        plan_title.spec=params[:ktitle][:spec]
        plan_title.group=params[:ktitle][:group]
        plan_title.kurs=params[:ktitle][:kurs]
        plan_title.semestr=params[:ktitle][:semestr]
        plan_title.god=params[:ktitle][:god]
        plan_title.uchregd=params[:ktitle][:uchregd]
        plan_title.ch_ned=params[:ktitle][:ch_ned].to_i
        plan_title.ch_zan=params[:ktitle][:ch_zan].to_i
        plan_title.ch_labrab=params[:ktitle][:ch_labrab].to_i
        plan_title.ch_kprtk=params[:ktitle][:ch_kprtk].to_i
        plan_title.ch_smr=params[:ktitle][:ch_smr].to_i
        plan_title.save
        redirect_to lib_path(:id=>(params[:ktitle][:kplan_id]).to_i)
      end

  def kp_lit
    id=params[:id]
    @klib=Klit.find_by_kplan_id(id)
    @error_messages=""
  end

      def save_lib
        plan_id=params[:klib][:kplan_id].to_i
        lib=Klit.find_by_kplan_id(plan_id)
        if lib.nil?
          lib=Ktitl.new(kplan_id:params[:klib][:kplan_id])
        end
        (1..24).each do |str|
          lib["literatura#{str}"]=params[:klib]["literatura#{str}"]
        end
        lib.save
        redirect_to body_path(:id=>plan_id)
      end


  def kp_body
    id=params[:id]
    @kbody=Kbody.where("kplan_id=?", id)
    @page_count= @kbody.empty? ? 0 : @kbody.maximum("nomer_page")
  end

    def save_body
    end

    def delete_body
    end

  def kp_view 
    id=params[:id]
    @title=Ktitl.find_by_kplan_id(id)
        # => @ktitle["ch_all"]=@ktitle.ch_zan.to_i + @ktitle.ch_labrab.to_i + @ktitle.ch_kprtk.to_i
    @body=Kbody.where("kplan_id=?", id)
    @lib=Klit.find_by_kplan_id(id)
  end

  def kp_print
    kplan_toprint=Kplan.find(params[:id])
      @ktitle=kplan_toprint.ktitl
        @ktitle["user"]=kplan_toprint.user.name
        @ktitle["ch_all"]=@ktitle.ch_zan.to_i + @ktitle.ch_labrab.to_i + @ktitle.ch_kprtk.to_i
      @klib=kplan_toprint.klit
      @kbody=kplan_toprint.kbody
      @kbody_0=Kbody.new
    pages_real=Kbody.where("kplan_id=?", params[:id]).maximum("nomer_page")
    pages_need= pages_real + (pages_real.even? ? 0 : 1 )
    @print_first=[]
    @print_second=[]
    range=pages_need/2-1
    range.times do |numb_srt|
      @print_first<<[((pages_need-numb_srt)>pages_real ? 0 : pages_need-numb_srt), numb_srt+2]
    end
    range=pages_need/2
    range.times do |numb_srt|
      @print_second<<[numb_srt+2, ((pages_need-numb_srt)>pages_real ? 0 :  pages_need-numb_srt)]
    end
  end

      def test_db #Заполнение бд тестовой инфой
        b=1
        a=Kplan.new(user_id:1)
        a.save
        a=Ktitl.new
          a.kplan_id=1
          a.pregmet="Очень длинное нзвание предмета, которое не уместилось в одну строку"
          a.spec="230105"
          a.group="244, 245"
          a.kurs="III"
          a.semestr="3"
          a.god="2012"
          a.uchregd="Методическим советом СПКВТК"
          a.ch_ned=17
          a.ch_zan=40
          a.ch_labrab=20
          a.ch_kprtk=12
          a.ch_smr=20
        a.save
        a=Klit.new
        a.kplan_id=1
        (1..20).each do |i|
          if i.odd?
            a["literatura#{i}"]="Описание источника из которого был взят для материала лекций"
          else
            a=Klit.new
            a["literatura#{i}"]="продолжение описание литературы, которое не уместилось в первую строку"
          end
        end
        a.save

    b=0
    (1..5).each do |str|
      a=Kbody.new(kplan_id:1, nomer_page:str)
      (1..26).each do |i|
        if i.odd?
            b=b+1
            a["nomer_uroka#{i}"]="#{b}"
            a["tema_zaniatia#{i}"]="#{str} - #{i} - #{a["nomer_uroka#{i}"]} Здесь написана тема занятия - первая строка"
            a["nomer_nedeli#{i}"]=b/2+1
            a["kolvo_chasov#{i}"]=rand((3)+1)*2
            a["vid_zaniatia#{i}"]="Вид занятия #{str}-#{i}"
            a["nagl_posobie#{i}"]="Наглядное посо-"
            a["zadano#{i}"]="Задано студен-"
            c=rand(2)*2
            if c>0
              a["samrab_casov#{i}"]=c.to_s
              a["samrab_zadanie#{i}"]="Задание для са-"
            else
              a["samrab_casov#{i}"]=""
              a["samrab_zadanie#{i}"]=""
            end
        else
            a["nomer_uroka#{i}"]=""
            a["tema_zaniatia#{i}"]="а дальше идет вторая строка текста, продолжение #{str} - #{i}"
            a["nomer_nedeli#{i}"]=""
            a["kolvo_chasov#{i}"]=""
            a["vid_zaniatia#{i}"]=""
            a["nagl_posobie#{i}"]="бие для #{str} - #{i}"
            a["zadano#{i}"]="там надом #{str} - #{i}"
            a["samrab_casov#{i}"]=""
            if i>1
              if a["samrab_zadanie#{i-1}"].empty?
                a["samrab_zadanie#{i}"]=""
              else
                a["samrab_zadanie#{i}"]="мостоятельной#{i}"
              end
            end
        end
        a.save
      end
    end

      end

  
end

app/helpers/plan_helper.rb
module PlanHelper
  
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

def current_user=(user)
    @current_user = user
  end  
  
  def current_user
    @current_user ||= user_from_remember_token
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
    
    def signed_in?
    !current_user.nil?
  end
end

app/views/plan/_body_list.html.erb
      <div class="all_body">
        <table>
          <% @body= @kbody.find_by_nomer_page(@page)%>
          <% @body= @body.nil? ? Kbody.new : @body %>
          <%=form_for :body do |f|%>
            <%= f.hidden_field :kplan_id%>
            <%= f.hidden_field :nomer_page%>

            <tr>
              <th class="d1">№ урока</th> 
              <th class="d2">Наименование разделов и тем</th> 
              <th class="d3">Номер недeли</th>
              <th class="d4">Кол-во часов</th> 
              <th class="d5">Вид занятий</th> 
              <th class="d5">Наглядные пособия</th>
              <th class="d5">Задание для студентов</th> 
              <th width="195px" colspan=2>Самостоятельная работа</th>
              <th class="d5">Удалить страницу</th>
            </tr>
            <%(1..26).each do |str|%>
            <tr>
              <td> <%= f.text_field "nomer_uroka#{str}" , :maxlength => 4, :class=>"i1" %> </td> 
              <td> <%= f.text_field "tema_zaniatia#{str}" , :maxlength => 46, :class=>"i2" %> </td> 
              <td> <%= f.text_field "nomer_nedeli#{str}"  , :maxlength => 5, :class=>"i3" %> </td>  
              <td> <%= f.text_field "kolvo_chasov#{str}" , :maxlength => 5, :class=>"i3" %> </td> 
              <td> <%= f.text_field "vid_zaniatia#{str}" , :maxlength => 15, :class=>"i4" %> </td>
              <td> <%= f.text_field "nagl_posobie#{str}" , :maxlength => 15, :class=>"i4" %> </td> 
              <td> <%= f.text_field "zadano#{str}" , :maxlength => 15, :class=>"i4" %> </td> 
              <td> <%= f.text_field "samrab_casov#{str}" , :maxlength => 4, :class=>"i1" %> </td> 
              <td> <%= f.text_field "samrab_zadanie#{str}" , :maxlength => 15, :class=>"i4" %> </td>
            </tr>
            <%end%>
            <% if @page==@page_count %>
                <tr><td colspan=9></td> <th class="d5">Добавить страницу</th></tr>
            <%end%>
          <% end %>
        </table>
      </div>  

app/views/plan/_info.html.erb
<div id="info_to_hide">
<h1>Электронный календарный план</h1>
<p></p>
<p>
Система, которая позволит вам создавать, моифицировать и централизованно хранить все ваши календарные планы, а также в два легких шага поможет распечатать готовый к сшиванию документ.</p>
<p> <a id="add_welcome">Зарегистрироваться</a>
Работать с сервисом могут только зарегистрированые пользователи, поэтому, если вы не имеете аккаунта, пожалуйста, зарегистрируйтесь.
</p>
</div>

app/views/plan/_welcome.html.erb
	<div class="reg_block" id="show_welcome">
		<%=form_for :user, :url => { :action => "createuser" } do |f|  %>
		
			<h1>Регистрация нового пользователя</h1>
			<table>
				<tr>
					<td>Ваша фамилия и инициалы</td>
					<td><%=f.text_field :name%></td>
				</tr>
				<tr>
					<td>Удобный для вас логин </td>
					<td><%=f.text_field :nik , :maxlength => 20, :class=>"i1" %></td>
				</tr>
				<tr>
					<td>Пароль</td>
					<td><%=f.password_field :pas , :class=> "i2"%></td>
				</tr>
				<tr>
					<td>Подтверждение пароля</td>
					<td><%=f.password_field :pas_confirmation, :class=>"i1" %></td>
				</tr>
				<tr>
					<td>Номер предметной комиссии </td>
					<td><%=f.text_field :predmet_comissia , :maxlength => 2,  :class=>"i3"%> (если вам он известен)</td>
				</tr>
			</table>
			<%= f.submit "Готово" , :class=>"button_submit" %>
			
		<%end%>
	</div>

app/views/plan/cabinet.html.erb
#encoding: utf-8

<div class="all_first">
	<div class="all_body">
		<p class="title"> Здравствуйте, <%=@user.name%> <p>
		<%= link_to "Создать новый календарный план",  title_path, :class=>"button_submit"%>	
		
		<table class="cabinet">
			<tr>
				<th> Название дисциплины </th>
				<th> Последняя редакция </th>
				<th colspan="4"> Действия </th>
			</tr>
			<%if @cabinet_plans.count==0%>
				<tr > <td class="d9">ничего не создано</td><td class="d7"></td>
					<td class="d8"></td><td class="d8"></td> </tr>
			<%else%>
				<%@cabinet_plans.each do |one_plan|%>
					<tr>
						<td class="d6"> <%=one_plan.ktitl.nil? ? "(без названия)" : one_plan.ktitl.pregmet%> </td>
						<td class="d7"> <%=one_plan.ktitl.nil? ? " " : format_plan_data(one_plan.ktitl.updated_at) %>  </td>
						<td class="plan_option"> просмотр </td>
						<td class="plan_option"> печатать </td>
						<td class="plan_option"> <%=link_to "редактировать", title_path(one_plan.id)%> </td>
						<td class="plan_option"> удалить </td>
					</tr>
				<%end%>
			<%end%>
		</table>
	</div>
</div>

app/views/plan/index.html.erb
#encoding: utf-8

<div class="all_first">
  <div class="first_blok">
	<%=form_for :session , :url => { :action => "createsession" } do |f|%>
		<h1>Вход для зарегистрированных пользователей</h1>
		<p>Логин <%=f.text_field :nik , :maxlength => 20, :class=>"i1" %></p>
		<p>Пароль <%=f.password_field :pas%></p>
		<%= f.submit "Войти" , :class=>"button_submit"%>
	<%end%>
  </div>
  <div class="info_blok">
		<%=render :partial=>'info'%>
		<%=render :partial=>'welcome'%>
  </div>

</div>

app/views/plan/kp_body.html.erb
#encoding: utf-8

<div class="all_first">
    <% for @page in (1..(@page_count==0 ? 1 : @page_count)) %>
      <%=render :partial=>'body_list'%>
    <%end%>
</div>

app/views/plan/kp_lit.html.erb
#encoding: utf-8

<div class="all_first">

   <div class="all_title">
       <div id="header">
            <p> СПИСОК  ЛИТЕРАТУРЫ </p>
       </div>
       <%= form_for :klib, :url => { :action => "save_lib" }  do |f|%>
          <%= f.hidden_field :kplan_id%>
          <%= @error_message %>
          <% (1..24).each do |str| %>
            <%= f.text_field "literatura#{str}", :maxlength => 80, :class=>"i17" %> 
          <%end%>
          <%= submit_tag "Сохранить"%>
        <% end %>

        <p> </p>
   </div>
</div>
<div>
  Место для кнопок
</div>

app/views/plan/kp_print.html.erb
#encoding: utf-8

<div class="all_first">
	<div class="first_blok">
		<a class="button_print"> Печать <br>ПЕРВОЙ стороны</a>
		<br>
		<a class="button_print"> Печать <br>ВТОРОЙ стороны</a>
  </div>
   <div class="info_blok">
	<h1>Пять простых шагов </h1>
	<p></p>
	<p>1. Нажмите кнопку "Печать первой стороны"</p>
	<p>2. Поля со всех сторон должны быть по 1 см, ориентация листа - альбомная</p>
	<p>3. Не разделяя напечатанную пачку листов, переверните ее другой стороной верх</p>
	<p>4. Нажмите кнопку "Печать второй стороны"</p>
	<p>5. Готово!</p>
  </div>
</div>


<div class="all_print">
	<div class="first_print">
		<table class="one_list">
			<tr>
				<td class="one_page" id="empty">© СПКВТК <%=Date.today.year%></td>
				<td class="center"> </td>
				<td class="one_page" id="title_page">
					<div id="header">
            			<p> СЕРГИЕВО-ПОСАДСКИЙ </p>
            			<p> КИНОВИДЕОТЕХНИЧЕСКИЙ КОЛЛЕДЖ </p>
      				</div>
      					<table id="mini">
        					<tr>
            					<td>
                  					<p> УТВЕРЖДАЮ </p>
                  					<p> Зам.директора по учебной работе </p> 
                  					<p> <big>                                           </big></p>
                  					<p> «<big>       </big>» <big>                   </big> 20<big>      </big> г.</p>
            					</td>
            					<td>
					                <p> Рассмотрено на заседании </p>
					                <p> предметной комиссии </p>
					                <p> «<big>       </big>» <big>                   </big> 20<big>      </big> г.</p>
					                <p> Протокол № <big>                         </big> </p>
					                <p>Председатель предметной комиссии</p>
					                <p> <big>                                                     </big></p>
					            </td>
        					</tr>
      					</table>
		      		<p id="title"> КАЛЕНДАРНЫЙ ПЛАН </p>
		      		<table class="left">
			            <tr><td class="discpl_name"> учебных занятий по предмету</td>
			            	<td class="discpl_data"><%= @ktitle.pregmet%> </td></tr>
			        </table>
			        <table class="left">    
			            <tr><td class="data_name"> для специальности</td>
			            	<td class="data"><%= @ktitle.spec%></td></tr>
			            <tr><td class="data_name"> Преподаватель</td>
			            	<td class="data"><%= @ktitle.user%></td></tr>
			            <tr><td class="data_name"> Группы</td>
			            	<td class="data"><%= @ktitle.group%></td></tr>
			        </table>
		            <table class="center">
		                <tr><td class="data_name">Курс </td>
			            	<td class="data"><%= @ktitle.kurs%></td></tr>
		                <tr><td class="data_name">Семестр</td>
			            	<td class="data"><%= @ktitle.semestr%></td></tr>
		                <tr><td class="data_name">Учебный год</td>
			            	<td class="data"><%= @ktitle.god%></td></tr>
		            </table>
		            <table class="center" id="dop">
		                <tr><td class="discpl_name">Составлено в соответствии с программой, утвержденной</td></tr>
		                <tr><td class="discpl_data"><%= @ktitle.uchregd%></td></tr>
		            </table>
		            <table class="midle" id="i1">
		                <tr><td class="data_name" > Число недель </td>
		                	<td class="data"><%= @ktitle.ch_ned%></td><tr> 
		             </table>
		            <table class="midle" id="i2">
		                <tr><td class="data_name" > Занятия на уроках</td>
		                <td class="data"><%= @ktitle.ch_zan%></td><td>час.</td><tr> 
		                <tr><td class="data_name" > Лабораторные работы</td>
		                <td class="data"><%= @ktitle.ch_labrab%></td><td>чаc.</td><tr> 
		                <tr><td class="data_name"> Курсовое проектирование</td>
		                <td class="data"><%= @ktitle.ch_kprtk%></td><td>час.</td><tr> 
		             </table>
		              <table class="midle" id="i3">
		                <tr><td class="data_name"> Всего</td>
		                <td class="data"><%= @ktitle.ch_all%></td><td>час.</td><tr> 
		             </table>
		              <table class="midle" id="i4">
		                <tr><td class="data_name"> Самостоятельная нагрузка студентов</td>
		                <td class="data"><%= @ktitle.ch_smr%></td><td>час.</td><tr> 
		             </table>
				</td>
			</tr>
		</table>

		<table class="one_list">
			<tr>
			<td class="one_page">
				<table>
					<tr><th>СПИСОК  ЛИТЕРАТУРЫ</th></tr>
					<%(1..25).each do |one_string|%>
						<tr> <td class="lit"><%=@klib.find_by_nomer_srt(one_string).present? ? @klib.find_by_nomer_srt(one_string).literatura : " "%> </td></tr>
					<%end%>
					<tr><td> <%=@ktitle.user%> <big>/______________________ /</big></td></tr>
				</table>
			</td>
			<td class="center"> </td>
			<td class="one_page">
				<table >
					<tr>
			            <th class="d5">Вид занятий</th> 
			            <th class="d5">Наглядные пособия</th>
			            <th class="d5">Задание для студентов</th> 
			            <th colspan=2>Самостоятельная работа</th>
          			</tr>
          			<%page= @kbody.where("nomer_page=1")%>
          			<%(1..26).each do |one_string|%>
          				<%string= page.find_by_nomer_str(one_string).present? ? page.find_by_nomer_str(one_string) : @kbody_0 %>
          				<tr>
          					<td> <%=areyounil(string.vid_zaniatia)%>  </td>
          					<td> <%=areyounil(string.nagl_posobie)%></td>
          					<td> <%=areyounil(string.zadano)%></td>
          					<td> <%=areyounil(string.samrab_casov)%></td>
          					<td class="d5"> <%=areyounil(string.samrab_zadanie)%></td>
          				</tr>
          			<%end%>
				</table>
			</td>
		</tr>
		</table>

		<%@print_first.each do |one_list|%>
			<table class="one_list">
				<tr>
					<td class="one_page"> 
						<table >
							<tr>
					            <th class="d1">№ урока</th> 
					            <th>Наименование разделов и тем</th> 
					            <th class="d3">Номер недeли</th>
					            <th class="d4">Кол-во часов</th> 
		          			</tr>
          					<%page= @kbody.where("nomer_page=?", one_list[0])%>
          					<%(1..26).each do |one_string|%>
          						<%string= page.find_by_nomer_str(one_string).present? ? page.find_by_nomer_str(one_string) : @kbody_0 %>
          						<tr>
		          					<td><%=areyounil(string.nomer_uroka)%>  </td>
		          					<td  class="d2"><%=areyounil(string.tema_zaniatia)%></td>
		          					<td> <%=areyounil(string.nomer_nedeli)%></td>
		          					<td> <%=areyounil(string.kolvo_chasov)%></td>
		          				</tr>
		          			<%end%>
						</table>
					</td>
					<td class="center"> </td>
					<td class="one_page"> 
						<table >
							<tr>
					            <th class="d5">Вид занятий</th> 
					            <th class="d5">Наглядные пособия</th>
					            <th class="d5">Задание для студентов</th> 
					            <th colspan=2>Самостоятельная работа</th>
		          			</tr>
          					<%page= @kbody.where("nomer_page=?", one_list[1])%>
          					<%(1..26).each do |one_string|%>
          						<%string= page.find_by_nomer_str(one_string).present? ? page.find_by_nomer_str(one_string) : @kbody_0 %>
          						<tr>
		          					<td> <%=areyounil(string.vid_zaniatia)%>  </td>
		          					<td> <%=areyounil(string.nagl_posobie)%></td>
		          					<td> <%=areyounil(string.zadano)%></td>
		          					<td> <%=areyounil(string.samrab_casov)%></td>
		          					<td> <%=areyounil(string.samrab_zadanie)%></td>
		          				</tr>
		          			<%end%>
						</table>
					</td>
				</tr>
			</table>
		<%end%>
	</div>

	<div class="second_print">
		<table class="one_list">
			<tr>
				<td class="one_page">
						<table >
							<tr>
					            <th class="d1">№ урока</th> 
					            <th >Наименование разделов и тем</th> 
					            <th class="d3">Номер недeли</th>
					            <th class="d4">Кол-во часов</th> 
		          			</tr>
          					<%page= @kbody.where("nomer_page=1")%>
          					<%(1..26).each do |one_string|%>
          						<%string= page.find_by_nomer_str(one_string).present? ? page.find_by_nomer_str(one_string) : @kbody_0 %>
          						<tr>
		          					<td> <%=areyounil(string.nomer_uroka)%>  </td>
		          					<td class="d2"> <%=areyounil(string.tema_zaniatia)%></td>
		          					<td> <%=areyounil(string.nomer_nedeli)%></td>
		          					<td> <%=areyounil(string.kolvo_chasov)%></td>
		          				</tr>
		          			<%end%>
						</table>
				</td>
				<td class="center"> </td>
				<td class="one_page">
					<table>
						<caption> КОНТРОЛЬ <br> выполнения календарного плана <br> председателем предметной комиссии </caption>
						<tr> <th>Дата</th><th>Замечание</th><th>Подпись</th></tr>
						<%23.times do%>
							<tr> <td></td><td></td><td></td></tr>
						<%end%>
					</table>
				</td>
			</tr>
		</table>
		<%@print_second.each do |one_list|%>
			<table class="one_list">
				<tr>
					<td class="one_page"> 
						<table >
							<tr>
					            <th class="d1">№ урока</th> 
					            <th>Наименование разделов и тем</th> 
					            <th class="d3">Номер недeли</th>
					            <th class="d4">Кол-во часов</th> 
		          			</tr>
          					<%page= @kbody.where("nomer_page=?", one_list[0])%>
          					<%(1..26).each do |one_string|%>
          						<%string= page.find_by_nomer_str(one_string).present? ? page.find_by_nomer_str(one_string) : @kbody_0 %>
          						<tr>
		          					<td> <%=areyounil(string.nomer_uroka)%>  </td>
		          					<td class="d2"> <%=areyounil(string.tema_zaniatia)%></td>
		          					<td> <%=areyounil(string.nomer_nedeli)%></td>
		          					<td> <%=areyounil(string.kolvo_chasov)%></td>
		          				</tr>
		          			<%end%>
						</table>
					</td>
					<td class="center"> </td>
					<td class="one_page"> 
						<table >
							<tr>
					            <th class="d5">Вид занятий</th> 
					            <th class="d5">Наглядные пособия</th>
					            <th class="d5">Задание для студентов</th> 
					            <th colspan=2>Самостоятельная работа</th>
		          			</tr>
          					<%page= @kbody.where("nomer_page=?", one_list[1])%>
          					<%(1..26).each do |one_string|%>
          						<%string= page.find_by_nomer_str(one_string).present? ? page.find_by_nomer_str(one_string) : @kbody_0 %>
          						<tr>
		          					<td> <%=areyounil(string.vid_zaniatia)%>  </td>
		          					<td> <%=areyounil(string.nagl_posobie)%></td>
		          					<td> <%=areyounil(string.zadano)%></td>
		          					<td> <%=areyounil(string.samrab_casov)%></td>
		          					<td> <%=areyounil(string.samrab_zadanie)%></td>
		          				</tr>
		          			<%end%>
						</table>
					</td>
				</tr>
			</table>
		<%end%>
	</div>

</div>